### ISSUE TITLE
404 Link

### ISSUE THREAD

**Issue by carlzoo** [autofac/Autofac.AspNetCore#2]
Nuget link leads to 404 - https://www.nuget.org/packages/Autofac.AspNetCore

Has the package been removed?

**Comment by alexmg** [comment]
We haven't actually released this package yet. At one stage we were considering adding some other ASP.NET Core related helpers for multitenant support in there but they ended up in a separate package. I have another helper method to add (easily allow for container disposal on ASP.NET Core application shutdown) and then it may be worth the effort of maintaining.
