### ISSUE TITLE
“Cannot instantiate implementation type” on ASP.NET Core's application startup

### ISSUE THREAD

**Issue by tillig** [autofac/Autofac.AspNetCore#4]
_From @thiagomajesk on June 1, 2018 17:8_

Hello guys...
Before I start, a little bit of context:

Some time ago, I've opened [this issue](https://github.com/aspnet/DependencyInjection/issues/531) about ASP.NET Core's default container supporting complex cases for generics. While this is not supported I've been managing to use AutoFac for some missing use-cases.

So, I'm having a problem while implementing some generic use-cases using the MediatR library and I'm not sure if the problem is related to AutoFac, my configuration or even ASP.NET Core.

I'm saying this because I'm suspicious that AutoFac is not being registered correctly and the default container is assuming the registration at some point. The reasoning behind that is the stack trace logging the exact same error message I had in the past.

```
Cannot instantiate implementation type
'Project.App.Base.Handlers.CreateEntityCommandHandler`2[TEntity,TCommand]' 
for service type 'MediatR.IRequestHandler`2[TCommand,TEntity]'.
```

I don't think is related to any specific configuration I've done because if I comment my configuration the error still occurs. I'm using the code in this template I'm creating: https://github.com/thiagomajesk/ASP.NET-Core-Bootstrap-Template. 
If you clone the repo and run the application you will see the error, it is thrown just after the application bootstrap.

**PS.:** Just FYI: I've recently ported the project to ASP.NET Core 2.1, so maybe there's something related.

**This is the full stack trace:**

       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.Populate(IEnumerable`1 descriptors)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory..ctor(IEnumerable`1 descriptors)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
       at Microsoft.Extensions.DependencyInjection.ServiceLookup.CompiledServiceProviderEngine..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngineCallback callback)
       at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
       at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services)
       at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
       at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
       at Project.Web.Program.Main(String[] args) in C:\Users\usr\Source\Repos\_archived\ASP.NET-Core-Bootstrap-Template\Project.Web\Program.cs:line 11

_Copied from original issue: autofac/Autofac#920_

**Comment by tillig** [comment]
As I mentioned on the [now deleted] StackOverflow question, we really need a more minimal repro. On StackOverflow you might have had a whole community of people that could help (which is why the issue template here urges folks to try StackOverflow); here you only get the two Autofac project owners, one of which (me) I know doesn't use MediatR... and if we have to dive into a big repro to debug your code, I'll be honest... given the 20+ integration libraries, the recent release of ASP.NET Core 2.1, and the ongoing issues and maintenance for all the projects here, knowing this is a "spare time" thing we do unpaid... this is going to be a low priority thing to investigate.

Sorry about that, but again, that's why we try to get folks onto StackOverflow.

**Comment by tillig** [comment]
Since this appears to be ASP.NET Core specific, not something with core Autofac, I'm going to move it to the appropriate repo.

**Comment by tillig** [comment]
Unfortunately I don't have guidance on how to troubleshoot this. You'll likely have to do literally the same steps I'll do:

- Look at the stack trace.
- Go through GitHub repos, use SourceLink, use dotPeek, etc. to try to trace back through what's happening.
- Dive down deep rabbit holes to reverse engineer what all the components are doing.
- Remove one line of code at a time from the repro until the issue stops happening to see if there's a particular component or registration causing the issue.
- Guess and poke at it.

There's no magic or hidden tricks here. That's why a very, very tiny repro where we can maybe eyeball it and offer a guess is easiest.

The minimal repro is also good because if you can remove as much as possible you can reduce the number of things to research.

**Comment by thiagomajesk** [comment]
@tillig Thank you for the direction... 
I've created the smallest repro possible with only the libs ASP.NET Core uses to bootstrap the application and could attest that the problem is not with AutoFac registration or configuration.
 
Actually, my suspicion that the problem was happening with the default DI container has confirmed.

The exact problem was calling the `IServiceCollection` extension: `services.AddMediatR()`. This seems to use the default container and not AutoFac's. I found this a bit misleading because of AutoFac's wiki:

> In the ConfigureServices method of your Startup class register things into the IServiceCollection using extension methods provided by other libraries. 

So I was under the impression that this extension would work with AutoFac's container, not the default one. (Like AutoFac was assuming the place of the default container).

What I did to solve my problem is: removing the MediatR registration on `IServiceCollection` and leaving it only to an AutoFac module (what actually makes sense).

**Comment by tillig** [comment]
Adding things to the services collection should be fine as long as you call `containerbuilder.Populate(services)` to transfer the registrations into the Autofac container. That's how everything else works. If you found that those registrations force the use of the default container you should file an issue with them because they've broken that contract.

Glad you figured it out!

**Comment by incredible-India** [comment]
this will help
builder.Services.AddTransient<Istudent , StudentService>(); 
...............
where 
StudentService : Istudent
