### ISSUE TITLE
Feature :  Model binding parameters from Autofac container

### ISSUE THREAD

**Issue by JonLopezGarcia** [autofac/Autofac.AspNetCore#5]
### Feature Request

In Asp.Net Core, it's possible to bind a parameter of an action from the built-in dependency injection with the use of the FromServices attribute.

It works also great when the autofac handles the dependency injection. 

The problem is that I cannot make use of ParameterFilter attribute to specify the injection of a keyed service with the FromService attribute.

I implemented a FromAutofacServices attribute that you can use with ParameterFilter derived attributes for the actions parameters.

example :
```csharp
 public IActionResult Get([FromAutofacServices] [KeyFilter("MyKey")] string myInjectedParameter){
     return Ok(myInjectedParameter);
 }
```

I would like to submit a pull request with that feature but I'm not sure on which repo I should submit it. This one seems appropriate but It's no longer available on the market.

**Comment by tillig** [comment]
This is the right repo, there just wasn't much value publishing a whole package that has a single extension method.

Is there a reason the injected item can't be a constructor dependency?

The reason I ask: adding features is awesome, but then it does add to the surface area of things we need to test, support, document, have examples for... There already being a `[FromServices]` attribute I'm wondering if you can solve the problem in a different way given things that exist.

Refactoring controllers to be more single-responsibility and not have a lot of actions, for example, both makes them easier to test and removes the need for action injection.

Alternatively, if you still think you need action injection, using `IIndex<String, Lazy<T>>` can allow you to look up the keyed item in the method body without resolving all of the keyed T instances and it'd work with the existing FromServices attribute.

That latter isn't super pretty, but I'm also guessing you don't have a lot of these.

What do you think?

**Comment by JonLopezGarcia** [comment]
I completely understand your opinion about adding features that are not intrinsically useful. I also think that we should design classes following the single responsibility principle that uncle Bob reminds us to follow.

To give a bit of a context, I'll expose my requirements. I have a web services in production that gives access to the entities of a relational database. Each controller exposes CRUD operations for one entity (except for some controllers who exposes operations). 

At the beginning, the web api was built to satisfy the needs of a specific project. However, we had in mind that it needed to be flexible enough to execute a different business logic based on a tenant sent by the caller. (The multi-tenant container fits great here !)

The need of a different business logic for a new client is specific to a certain endpoint (action) and not for the entire controller. If I put all the business implementations for a specific controller inside one class, I will have to inherit from that class and only override the methods that I want to customize. I don't like that... I prefer composition over inheritance.

Instead of this, I would like to split my business layer and encapsulate the business logic for each action behind its own implementation of a facade interface. Also, rather than injecting all the business classes in the constructor, I want to inject them inside the action so it's not only easier to test them, but again reduce the responsibility of the action to be the place where the business logic and the payload meet and optionally return something. 

Because of the fact that I'm going to implement several times the same facade interface, so I can switch implementations on demand ( and for the reasons explained above ), the only "proper" way that I have, in my humble opinion, to get the correct business injected inside my action is to use one of the parameter filter attributes available.

My actions will kind of look like this :

```csharp
public IActionResult Post( 
    [FromAutofacServices] [KeyFilter("PostClient")] IExecutionFacade businessLogic,
    [FromBody] ClientCreationPayload payload) {
    
    var result = businessLogic.Execute(payload);
    return result =! null ? Ok(result) : NoContent();

}
```

If the action returns a response, it means that all went well. If an exception is thrown inside the "Execute" method, it will be handled by my error handler middleware.

I hope I correctly exposed my ideas and therefore you understand my choices. 
I'm very interested in your feedback about my architecture and I hope you will challenge it so I can improve it.

**Comment by tillig** [comment]
> The need of a different business logic for a new client is specific to a certain endpoint (action) and not for the entire controller. If I put all the business implementations for a specific controller inside one class, I will have to inherit from that class and only override the methods that I want to customize. I don't like that... I prefer composition over inheritance.

While I recognize this preference of "composition over inheritance" it implies that you are very necessarily _not_ following single responsibility principle.

Plus, it seems like you could have this in a single controller:

```csharp
public class MyController
{
  public IActionResult Post(...) { }
}
```

If there's common logic, that could go in extension methods or a base class. The extension method mechanism is pretty composable and bypasses the bit you dislike of having a derived class.

Of course, you don't have to implement every verb on every controller. One could have GET, one could have POST... no need to share everything, which gets past your desire to "only override the methods that you want to customize." Don't have base methods to override.

I also see you mentioned...

> I'm going to implement several times the same facade interface, so I can switch implementations on demand

It doesn't look like you're switching them on demand. It looks like you've chosen a particular key and it's always that one that will get used (the one keyed `PostClient`). Seems like you could address switching by configuration or by using something like the multitenant container rather than needing filter attributes.

But let's even just ignore that. Have you tried just using the built-in stuff?

```csharp
public IActionResult Post(
  [FromServices] IIndex<string, Lazy<IExecutionFacade>> facades,
  [FromBody] ClientCreationPayload payload)
{
    var businessLogic = facades["PostClient"].Value;
    var result = businessLogic.Execute(payload);
    return result ? Ok(result) : NoContent();
}
```

Like I said before, maybe it's not as pretty as the strung-together-attribute mechanism, but it uses what's already available and still gets you what you have decided is the solution you want.

**Comment by tillig** [comment]
Closing this issue since there are ways to get this stuff using `[FromServices]` and since the generic hosting mechanism being introduced will make the stuff in `AutofacWebHostBuilderExtensions` obsolete.
