### ISSUE TITLE
Getting error Autofac.Core.Registration.ComponentNotRegisteredException

### ISSUE THREAD

**Issue by jaydeept** [autofac/Autofac.AspNetCore#8]
While using Autofac for .Net Core 2.2, I am getting below exception:

> OneTimeSetUp: Autofac.Core.Registration.ComponentNotRegisteredException : The requested service 'Microsoft.Extensions.Logging.ILogger`1[[Microsoft.AspNetCore.Hosting.Internal.WebHost, Microsoft.AspNetCore.Hosting, Version=2.2.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]' has not been registered. To avoid this exception, either register a component to provide the service, check for service registration using IsRegistered(), or use the ResolveOptional() method to resolve an optional dependency.
>   Exception doesn't have a stacktrace

Why should I register Microsoft service in my application?

**Comment by tillig** [comment]
Looks like you're using the Microsoft WebHost and it wants to log. When it tries to get an `ILogger<WebHost>` it's not found, which means you don't have the Microsoft logging registered. If you use their stuff, you have to register their dependencies.
